pipeline:
  build:
    image: productionwentdown/android-builder
    when:
      event: push
  release-build:
    image: productionwentdown/android-builder
    secrets: [ store_file, store_password, key_alias ]
    commands:
    - release
    when:
      event: tag
  release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: app/build/outputs/apk/release/app-release.apk
    when:
      event: tag
